package com.leonnewton.databaseopre;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.leonnewton.databaseopre.Msg;

import com.leonnewton.databaseopre.MsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgDaoConfig;

    private final MsgDao msgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgDaoConfig = daoConfigMap.get(MsgDao.class).clone();
        msgDaoConfig.initIdentityScope(type);

        msgDao = new MsgDao(msgDaoConfig, this);

        registerDao(Msg.class, msgDao);
    }
    
    public void clear() {
        msgDaoConfig.clearIdentityScope();
    }

    public MsgDao getMsgDao() {
        return msgDao;
    }

}
